# Site
repository: samanthasains/samanthasains.github.io
favicon: images/favicon-16x16.png

# Content configuration version
version: 2

# Personal info
name: Samantha Sainsbury
title: Transformational Change Consultant
email: samanthasains@gmail.com
# email_title: Email (Email title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  samanthasains
linkedin_username: samanthasainsbury

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile-2.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a mission-driven leader and believe in the capacity of groups and individuals to create their own change. My past experience has focused on project management and group facilitation, in which I leveraged my skill and interest in data storytelling to complement collective action and decision-making. I am seeking to pivot to a role where I can expand my data skills while still supporting social purpose work, ensuring that clients have the ability to make decisions informed by the most accurate and accessible data available.

content:
  - title: Class Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Bird Migration 
        link: github.com/samanthasains/Bird_Migration
        link_text: GitHub Repository
        quote: >
          This project used bird migration data from US Fish and Wildlife to generate an interactive map showing bird counts for 10 bird species in six different regions
        description: | # this will include new lines to allow paragraphs
          - Core Responsibilities: Wrote code for Flask App to render database visualizations
          - Languages: Python, HTML, JavaScript, CSS
      - layout: left
        title: Riverdale Ship Wars
        link: https://github.com/samanthasains/RDShipWars
        link_text: GitHub Repository
        quote: >
          This project applied sentiment analysis to twitter data to compare the sentiments about four different ‘ships’ from the CW’s Riverdale. 
        description: | # this will include new lines to allow paragraphs
          - Core Responsibilities: Wrote python code to pull data from Twitter, clean raw data, and iterate through CSV files to generate graphs
          - Languages/Tools: Python, Tweepy, JavaScript, HTML, CSS
      - layout: left
        title: Candyology
        link: https://github.com/samanthasains/candyology
        link_text: GitHub Repository
        quote: >
          This project used candy-related data from Kaggle and a candy wholesaler’s website to answer questions about candy consumption, production, and preferences.
        description: | # this will include new lines to allow paragraphs
          - Core Responsibilites: Wrote Python code to generate charts and graphs
          - Languages: Python
  
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Freelance
        sub_title: Facilitator and Facilitation Training
        caption: Jan. 2021 - present
        quote: >
          I co-design and facilitate spaces for groups, ranging from more effective and participatory meetings to short- and long-term plans of action.
        description: | 
          - Co-design and co-train online facilitation courses to build capacity of clients
            - [TFM Online](https://www.top-training.net/w/courses/46-top-facilitation-methods-online)
            - [Shift Happens](https://www.top-training.net/w/courses/38-shift-happens-design-principles-for-a-virtual-world)
          - Provide custom group facilitation, in-person and online, to enable groups to collectively think, make decisions, and take action
      - layout: right
        title: Institute of Cultural Affairs
        sub_title: |
          Program Manager
          Program Coordinator
          AmeriCorps Member
        caption: |
          March 2019 - Jan. 2021
          Aug. 2015 - March 2019
          Sept. 2014 - July 2015
        link: www.ica-usa.org
        quote: >
          The ICA is a capacity-building nonprofit at the intersection of social justice and environment. They use participatory facilitation to enable community groups to come to a shared awareness and make collective decisions.
        description: | # this will include new lines to allow paragraphs
          Project Management
          - Designed project evaluation metrics and analyzed results to document impact, identify successful program elements, and suggest future adaptations
          - Tracked and reported grant budgets and project outputs on a quarterly basis
          - Compiled two final project toolkits by writing project overviews, coordinating with internal partners and graphic designers, and providing final project recommendations
            - [Preparing for Rainy Days: Culturally-Inspired Smart Grid Education in 3 Communities](https://drive.google.com/file/d/1UPahBxJsZYCtTM9L79lCtgFQHhbwVe8l/view?usp=sharing)
            - [Out and About Uptown's Coast: A Toolkit on Designing Coastal and Environmental Education](https://drive.google.com/file/d/1uhuyUXJaN5wfWOtkJSzo_ZS5T58eE4Wz/view?usp=sharingf)
          
          Facilitation
          - Provided facilitation and event design expertise within internal programming and to community partners, including nine environmental education workshops, two participatory conferences, three strategic plans, two action plans, and 30+ community meetings
          - Completed multi-year portfolio and assessment for [Certified Technology of Participation (ToP) Facilitator](https://www.top-training.net/w/services/)
          - Co-trained six two-day ToP Facilitation Methods courses to become [ToP Qualified Trainer](https://www.top-training.net/w/privateevent/)
          
          Nework Building
          - Provided administrative support to national Technology of Participation trainer network with annual reporting on course scheduling and registrant data
          - Co-organized [sustainability network across Chicago](https://chicagoleaders.net/), including scheduling and designing bi-monthly network meetings, communication to membership, surveying network health, and supporting ongoing strategy
      - layout: right
        title: Institute of Cultural Affairs International
        sub_title: Board of Directors, Treasurer
        caption: Jan. 2019 - July 2021
        link: www.ica-international.org
        quote: >
          A global community of non-profit organisations advancing human development worldwide. ICA is about empowering, an authentic and sustainable transformation of individuals, communities and organizations, through methods and values.
        description: |
          - Prepared regular finance reports to board and General Assembly
          - Updated financial documentation system with increased automation
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Northwestern University
        sub_title: Bootcamp Certificate in Data Science and Visualization
        caption: March 2021
        description: |
          24-week intensive focused on data analytics fundamentals, including Intermediate Excel (pivot tables, VBA), Python, databases (SQL, MongoDB), front end development (HTML, CSS, JavaScript), Tableau, GitHub
      - layout: top-right
        title: Northwestern University
        sub_title: Bachelor of Arts in Sociology and Gender and Sexuality Studies
        caption: June 2014
          
  - title: Interests
    layout: text
    content: | # this will include new lines to allow paragraph
      In my free time, I enjoy reading (find me on [GoodReads](https://www.goodreads.com/user/show/61897931-samantha-sainsbury)!), baking ([some of my favorite bakes](https://photos.app.goo.gl/6xVN3o8VHvS1EvwLA)), musical sketch comedy, acting, and CrossFit.
      
      I also serve the demands of a small, tuxedo cat.
      
      ![tuxedo-cat-meowing](/images/kitty_resized.jpg "tuxedo-cat-meowing")
      

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
